language: java
jdk:
- openjdk8
- oraclejdk8
- openjdk7
- oraclejdk7
- openjdk6
before_install:
- openssl aes-256-cbc -K $encrypted_69bfa2df8b89_key -iv $encrypted_69bfa2df8b89_iv
  -in src/test/resources/travis.key.enc -out src/test/resources/api.key -d
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V